############################################################
####      HomeAssistant Configuration by J-Lindvig      ####
############################################################

#### A
automation: !include automations.yaml
automation old: !include_dir_merge_list include/automations/

#### C
config:

#### D
default_config:
device_tracker: !include include/device_trackers.yaml

#### F
ffmpeg:
frontend:
  themes: !include_dir_merge_named themes

#### H
homeassistant:
  customize: !include_dir_merge_named include/customize/
  packages: !include_dir_merge_named include/packages/

##### L
light: !include_dir_merge_list include/lights/
lovelace:
  mode: yaml
  resources: !include_dir_merge_list include/resources/

lovelace_gen:

#### R
recorder:
  db_url: !secret MYSQL_URL

remote_homeassistant:
  instances:
  - host: 192.168.0.13
    port: 8123
    secure: false
    verify_ssl: false
    access_token: !secret REMOTE_HA_API
    include:
      domains:
      - light
      - switch
      - sensor

rest_command: !include_dir_merge_named include/rest_commands/

#### S
shell_command: !include_dir_merge_named include/shell_commands/

#### T
tts:
  - platform: google_translate
    language: "da"

tuya:
  username: !secret TUYA_USERNAME
  password: !secret TUYA_PASSWORD
  country_code: !secret TUYA_COUNTRY
  platform: smart_life

#### V
var: !include_dir_merge_named include/variables/